# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'Potty Finder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Potty Finder
  
    pod 'CLTypingLabel', '~> 0.4.0'
    pod 'Firebase/Auth'
    pod 'Firebase/Firestore'
    pod 'IQKeyboardManagerSwift'

end
